apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "256Mi"
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: rc1a-jbpdcbnq4atgtfdm.mdb.yandexcloud.net
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              value: dbPassw0rd

---
apiVersion: v1
kind: Service
metadata:
  name: pma-service
spec:
  selector:
    app: phpmyadmin
  ports:
  - port: 8080
    targetPort: 80
  type: LoadBalancer